// Message: {
//   channelId: '1417419927408873523',
//   guildId: '1386396696241770516',
//   id: '1426307102250373222',
//   createdTimestamp: 1760128512681,
//   type: 0,
//   system: false,
//   content: 'anization.\n\nYours in utmost seriousness,\n\n[Your Name]\nHR Representative',
//   author: ClientUser {
//     id: '1032676226223063050',
//     bot: true,
//     system: false,
//     flags: UserFlagsBitField { bitfield: 0 },
//     username: 'Troll Bot',
//     globalName: null,
//     discriminator: '4606',
//     avatar: '9fe6760c04527437d62280a635122d2c',
//     banner: undefined,
//     accentColor: undefined,
//     avatarDecoration: null,
//     avatarDecorationData: null,
//     verified: true,
//     mfaEnabled: false
//   },
//   pinned: false,
//   tts: false,
//   nonce: null,
//   embeds: [],
//   components: [],
//   attachments: Collection(0) [Map] {},
//   stickers: Collection(0) [Map] {},
//   position: null,
//   roleSubscriptionData: null,
//   resolved: null,
//   editedTimestamp: null,
//   reactions: ReactionManager { message: [Circular *1] },
//   mentions: MessageMentions {
//     everyone: false,
//     users: Collection(0) [Map] {},
//     roles: Collection(0) [Map] {},
//     _members: null,
//     _channels: null,
//     _parsedUsers: null,
//     crosspostedChannels: Collection(0) [Map] {},
//     repliedUser: null
//   },
//   webhookId: null,
//   groupActivityApplication: null,
//   applicationId: null,
//   activity: null,
//   flags: MessageFlagsBitField { bitfield: 0 },
//   reference: null,
//   interactionMetadata: null,
//   interaction: null,
//   poll: null,
//   messageSnapshots: Collection(0) [Map] {},
//   call: null
// }
