const { summarizeMessages } = require("./aiSummary");
const config = require("../../config.json");

class DailyScheduler {
  constructor(client) {
    this.client = client;
    this.isRunning = false;
    this.scheduler = null;
  }

  start() {
    if (this.isRunning) {
      console.log("📅 Daily scheduler is already running");
      return;
    }

    this.isRunning = true;
    this.scheduleDailySummary();
    console.log("📅 Daily scheduler started");
  }

  stop() {
    if (this.scheduler) {
      clearTimeout(this.scheduler);
      this.scheduler = null;
    }
    this.isRunning = false;
    console.log("📅 Daily scheduler stopped");
  }

  scheduleDailySummary() {
    const now = new Date();
    const targetTime = new Date();
    targetTime.setHours(9, 0, 0, 0); // 9:00 AM

    // If it's already past 9 AM today, schedule for tomorrow
    if (now >= targetTime) {
      targetTime.setDate(targetTime.getDate() + 1);
    }

    const timeUntilNext = targetTime.getTime() - now.getTime();

    console.log(`📅 Next daily summary scheduled for: ${targetTime.toLocaleString()}`);

    this.scheduler = setTimeout(() => {
      this.postDailySummary();
      this.scheduleDailySummary(); // Schedule next day
    }, timeUntilNext);
  }

  async postDailySummary() {
    try {
      console.log("🌅 Generating daily summary...");

      const sourceChannelIds = config.sourceChannelIds;
      const summaryChannelId = config.chatSummaryChannelId;
      // Look back 3 days instead of 24 hours to ensure we find messages
      const threeDaysAgo = Date.now() - 3 * 24 * 60 * 60 * 1000;

      let allMessages = [];
      let totalMessagesFetched = 0;

      // Fetch messages from all source channels - use smaller limits for TinyLlama
      for (const id of sourceChannelIds) {
        const channel = this.client.channels.cache.get(id);
        if (!channel) continue;

        try {
          const fetched = await channel.messages.fetch({ limit: 20 }); // Reduced from 50 to 20
          totalMessagesFetched += fetched.size;

          const messages = [...fetched.values()].filter(
            (msg) =>
              !msg.author.bot && // Exclude bot messages
              msg.createdTimestamp > threeDaysAgo &&
              msg.content.length > 10 && // Reduced from 15 to 10
              !msg.content.startsWith("!") && // Exclude commands
              !msg.content.startsWith("/") && // Exclude slash commands
              !msg.content.match(/^[^\w]*$/) && // Exclude symbol-only messages
              !msg.content.toLowerCase().includes("good morning") && // Exclude greetings
              !msg.content.toLowerCase().includes("good night") &&
              !msg.content.toLowerCase().includes("bye") &&
              msg.content.length < 200 // Reduced from 500 to 200
          );

          allMessages = allMessages.concat(messages);
        } catch (error) {
          console.error(`Error fetching messages from channel ${id}:`, error);
        }
      }

      if (allMessages.length === 0) {
        await this.postEmptySummary();
        return;
      }

      // Take only the 20 most recent substantial messages - reduced for TinyLlama
      const recentMessages = allMessages
        .sort((a, b) => a.createdTimestamp - b.createdTimestamp)
        .slice(-20);

      // Create a mock interaction for the summarizeMessages function
      const mockInteraction = {
        editReply: async (message) => {
          console.log("📝 Summary progress:", message);
        },
      };

      const summary = await summarizeMessages(recentMessages, mockInteraction);

      await this.postSummary(summary, recentMessages.length, totalMessagesFetched);
    } catch (error) {
      console.error("❌ Error in daily summary:", error);
      await this.postErrorSummary();
    }
  }

  async postSummary(summary, processedCount, totalCount) {
    const summaryChannel = this.client.channels.cache.get(config.chatSummaryChannelId);
    if (!summaryChannel) {
      console.error("❌ Summary channel not found");
      return;
    }

    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const embed = {
      color: 0x00ff00, // Green
      title: `🌅 Daily Team Summary - ${today}`,
      description: summary,
      fields: [
        {
          name: "📊 Activity Stats",
          value: `• Messages processed: ${processedCount}/${totalCount}\n• Channels monitored: ${config.sourceChannelIds.length}\n• Timeframe: Last 3 days`,
          inline: true,
        },
        {
          name: "⏰ Generated",
          value: new Date().toLocaleTimeString("en-US", {
            hour: "2-digit",
            minute: "2-digit",
          }),
          inline: true,
        },
      ],
      footer: {
        text: "🤖 Generated by Juno Bot",
      },
      timestamp: new Date(),
    };

    try {
      await summaryChannel.send({ embeds: [embed] });
      console.log("✅ Daily summary posted successfully");
    } catch (error) {
      console.error("❌ Error posting daily summary:", error);
    }
  }

  async postEmptySummary() {
    const summaryChannel = this.client.channels.cache.get(config.chatSummaryChannelId);
    if (!summaryChannel) {
      console.error("❌ Summary channel not found");
      return;
    }

    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const embed = {
      color: 0xffa500, // Orange
      title: `🌅 Daily Team Summary - ${today}`,
      description:
        "📭 No substantial messages found in the last 3 days. The team might be quiet or on vacation!",
      fields: [
        {
          name: "📊 Activity Stats",
          value: `• Messages processed: 0\n• Channels monitored: ${config.sourceChannelIds.length}\n• Timeframe: Last 3 days`,
          inline: true,
        },
        {
          name: "⏰ Generated",
          value: new Date().toLocaleTimeString("en-US", {
            hour: "2-digit",
            minute: "2-digit",
          }),
          inline: true,
        },
      ],
      footer: {
        text: "🤖 Generated by Juno Bot",
      },
      timestamp: new Date(),
    };

    try {
      await summaryChannel.send({ embeds: [embed] });
      console.log("✅ Empty daily summary posted successfully");
    } catch (error) {
      console.error("❌ Error posting empty daily summary:", error);
    }
  }

  async postErrorSummary() {
    const summaryChannel = this.client.channels.cache.get(config.chatSummaryChannelId);
    if (!summaryChannel) {
      console.error("❌ Summary channel not found");
      return;
    }

    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const embed = {
      color: 0xff0000, // Red
      title: `🌅 Daily Team Summary - ${today}`,
      description: "❌ Error generating daily summary. The AI service might be unavailable.",
      fields: [
        {
          name: "📊 Status",
          value: "Failed to generate summary",
          inline: true,
        },
        {
          name: "⏰ Generated",
          value: new Date().toLocaleTimeString("en-US", {
            hour: "2-digit",
            minute: "2-digit",
          }),
          inline: true,
        },
      ],
      footer: {
        text: "🤖 Generated by Juno Bot",
      },
      timestamp: new Date(),
    };

    try {
      await summaryChannel.send({ embeds: [embed] });
      console.log("⚠️ Error daily summary posted");
    } catch (error) {
      console.error("❌ Error posting error daily summary:", error);
    }
  }
}

module.exports = DailyScheduler;
